import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css";
import { AuthProvider } from "./components/AuthProvider";
import Header from './components/Header';
import Footer from './components/Footer';
import { Toaster } from 'react-hot-toast';;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ZZ_2hand",
  description: "Generated by me",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AuthProvider>
          <Header />          
          {children}        
          <Toaster position="top-right" reverseOrder={false} />
          <Footer /> 
        </AuthProvider>
      </body>
    </html>
  );
}
